language: generic
sudo: required
services:
    - docker
dist: trusty
before_install:
    - docker build -t samnoh/react-app -f Dockerfile.dev .
script:
    - docker run -e CI=true samnoh/react-app npm test
